### ISSUE TITLE
.proto file name doesn't match what --generate expects

### ISSUE THREAD

**Issue by alecholmez** [DecipherNow/gm-fabric-go#101]
I created a service called `adl-service` and the proto file was named `adl-service.proto`

but the `--generate` step of fabric expected the proto file name to be `adl_service.proto` so it was throwing an error

**Comment by joshua-rutherford** [comment]
Good catch.  We can either inject a new value when rendering the template for that or we can have a more robust template that handles it.

**Comment by dougfort** [comment]
see https://github.com/DecipherNow/gm-fabric-templates/issues/3

I'm working on it

**Comment by dougfort** [comment]
This is  fixed by #103
