### ISSUE TITLE
method file names are clunky

### ISSUE THREAD

**Issue by alecholmez** [DecipherNow/gm-fabric-go#102]
While there is nothing wrong with this:
<img width="316" alt="screen shot 2018-01-11 at 1 14 49 am" src="https://user-images.githubusercontent.com/5223714/34811055-e71d9b54-f66c-11e7-95d5-9b03487d4c20.png">

I personally think they are clunky.

My proto definition:
```protobuf
service AdlService {
    rpc GetADLS(Empty) returns (ADLs) {
        option (google.api.http) = {
            get: "/adls"
        };
    }

    rpc CreateADL(ADL) returns (ADL) {
        option (google.api.http) = {
            post: "/adl"
        };
    }

    rpc GetADL(ADLReq) returns (ADL) {
        option (google.api.http) = {
            get: "/ald/{id}"
        };
    }
}
```

**Comment by joshua-rutherford** [comment]
Agree that it is sub optimal but I'm not sure how to intuit between something like 'GetADL' and ''GetALife' where the former should be 'get_adl' and the latter 'get_a _life'. 

I guess we could prompt the user with what we think it should be and let them override a la 'Enter file name for GetADL [get_a_d_l]:'.

**Comment by dougfort** [comment]
I like lower case filenames, so that's what I created. 

But we could use the method name as the file name.
```bash
GetADLS.go
CreateADL.go
GetADL.go
```

This has the advantage that wecan count on them being unique.
