### ISSUE TITLE
Add --ensure to fabric

### ISSUE THREAD

**Issue by dougfort** [DecipherNow/gm-fabric-go#104]
The current implementation of fabric fetches the templates once at ```--init```. I think there is a use case for re-fetching the templates without starting over. 

This would be
```bash
fabric --dir=<top dir> --ensure $SERVICE_NAME \
	--template git@github.com:deciphernow/gm-fabric-templates.git//default
``` 
The goal would be to bring the templates up to date, similar to ```dep ensure```

**Comment by joshua-rutherford** [comment]
Yeah, but this is always problematic.  That is, once on disk, users may make any number of changes to a file and reapplication of templates (even the original) would lose those.  I'm not sure there is a clean merge strategy but I'm open to suggestions.

**Comment by dougfort** [comment]
I don't have a clean merge strategy. I would say "you change it, you own it".  

But I think you are pointing to a larger issue.  How far do we support our generated code?  Once you run ```--init``` you're on your own? Or do we send out upgrades and bug fixes?

We could ship a JSON map listing template names an hashes. This would enable us to detect user changes. We could digitally sign the hash map to assure the user they are getting the templates they are supposed to get.
