### ISSUE TITLE
Add an optional copyright to generated code

### ISSUE THREAD

**Issue by dougfort** [DecipherNow/gm-fabric-go#105]
Each of our (non-generated) source files begins with a copyright notice. We could give our users the ability to supply their own copyright in a text file. (We might include our own "this code was generated by...").

**Comment by joshua-rutherford** [comment]
These are the kinds of customizations that using external templates makes easy.  For license headers and files though they are ubiquitous enough that it may make sense.

**Comment by dougfort** [comment]
I was thinking of something like ```{{.Copyright}}``` at the top of each template.  The content could be blank.
