### ISSUE TITLE
Configuration file option is unexpectedly parsed.

### ISSUE THREAD

**Issue by joshua-rutherford** [DecipherNow/gm-fabric-go#110]
Since Viper automatically discovers the file format (I assume based upon extension) we strip the extension when config files are specified at the command line: https://github.com/DecipherNow/gm-fabric-go/blob/master/cmd/fabric/config/config.go#L136

However, our current implementation assumes only as single `.` in the file name.  In practice there is no requirement that files contain only one `.` and thus when I try to provide `--config ./settings.toml.second` we still process the `./settings.toml` file because of this assumption. 

I think a more reasonable approach is to assume that the extension follows the last `.` in a file name. I think that this can be accomplished by changing the above line to:

```
viper.SetConfigName(strings.TrimSuffix(filepath.Base(configFilePath), filepath.Ext(configFilePath))
```

I personally think this is a bad implementation on Viper's part as file extensions are totally irrelevant so the full name should be provided but that argument is for another day.

**Comment by joshua-rutherford** [comment]
Note, that I have not confirmed that Viper treats this properly (i.e., if it expects a specific extension then this doesn't work).  I would totally be willing to put some effort into making Viper do the right thing.

**Comment by joshua-rutherford** [comment]
Looks like Viper supports setting config file type explicitly and reading a buffer.  My guess is we standardize on the accepted formats for settings and then use this method.

**Comment by dougfort** [comment]
I was trying to give the developer maximum flexibility. But since we are pretty rigid about what we want in the config file, that doesn't make much sense.

**Comment by joshua-rutherford** [comment]
I am actually completely okay with flexibility.  I would love for Viper to just accept the filename with extension and go from there.  No need to have it search for the extensions it knows.  I'm okay trying to get that upstream.
