### ISSUE TITLE
Add Prometheus Observer to  Metrics Server

### ISSUE THREAD

**Issue by dougfort** [DecipherNow/gm-fabric-go#117]
[gometrics](https://github.com/armon/go-metrics) has the concept of 'sinks'.

> The metrics package makes use of a MetricSink interface to support delivery to any type of backend. 

We're currently using the statsite sink in an Observer. We could easily make another observer that supports PrometheusSink. 

[Prometheus](http://prometheus.io/) would give us a quick way to save metrics.

**Comment by joshua-rutherford** [comment]
No, we have a quick way to save metrics right now using statsd.  I just need to deploy it.
