### ISSUE TITLE
CI failing on bad import

### ISSUE THREAD

**Issue by dougfort** [DecipherNow/gm-fabric-go#119]
CircleCI is failing on a change to ```gm-fabric-go/gk```: https://circleci.com/gh/DecipherNow/gm-fabric-go/139
```
cd ~/.go_workspace/src/$IMPORT_PATH && go get ./...
# github.com/deciphernow/gm-fabric-go/gk
gk/pkg.go:195:56: undefined: zk.WithLogger

cd ~/.go_workspace/src/$IMPORT_PATH && go get ./... returned exit code 2

Action failed: cd ~/.go_workspace/src/$IMPORT_PATH && go get ./...
```
But the code compiles on my machine and the function is present in the latest master on github
```
https://github.com/samuel/go-zookeeper/blob/master/zk/conn.go#242
```
I think that either CircleCI doesn't have the latest version of ```samuel/go-zookeeper/blob/master/zk``` or it doesn't have it at all. 

I could use help in fixing this

**Comment by joshua-rutherford** [comment]
I rebuilt this without the cache and it passed so I suspect @dougfort was correct on this one.
