### ISSUE TITLE
Generate fabric for a specific version of gm-fabric-go

### ISSUE THREAD

**Issue by dougfort** [DecipherNow/gm-fabric-go#124]
The generated code needs to bring a known release of gm-fabric-go into its vendor directory.

If the fabric generator calls ```dep --init```, we will get the most recent tagged version from the ```deciphernow``` GitHub repository.

For more flexibility, I suggest adding a ```--fabric-version``` command line argument

It can have these values
 * **current** = the most recent tagged version (default)
 * **vn.nn** = a specific tagged version such as v0.1.1
 * **xxx** = anything else will be treated as a branch name such as ```master```, ```fix-syntax-error```

**Comment by alecholmez** [comment]
There are commands within dep that let you change the version of the vendored dependency. Do we really need to do this?

**Comment by dougfort** [comment]
I want to be able to run the automated tests of the fabric generator while developing.  
Right now my procedure is:
 * run the test
 * let it fail;
 * copy my local gm-fabric-go into vendor/github.com/deciphernow
 * pick up the test script where it died.

So, I want to run those "commands within dep that let you change the version of the vendored dependency" during the test.

There is a similar issue with the templates, but it's wasier to deal with.

**Comment by dougfort** [comment]
replaced by #128
