### ISSUE TITLE
Generated init.py could be updated with recent changes 

### ISSUE THREAD

**Issue by lucasmoten** [DecipherNow/gm-fabric-go#135]
The following are recommended, based upon what was done for object-drive, and the audit consumers

* Use the logging library and logging.debug, or appropriate level in place of print statements
* If claiming to be locked, actually check to see if corresponding process is running. Cleanup as appropriate
  * If comparing to object drive or audit consumers, you'll see references to handle lockfile and oldlockfile. You can ignore those
* May want to improve call to stop to return codes that get picked up and handled depending on scenario to support graceful restarts that encountered an error during stop.  
* When calling subprocesses, set shell=False. 
  * The shell_source definition in object drive provides a way to emulate what is being done, as well as handling variable expansion
* When reporting that the service is running, also display the pid

**Comment by alecholmez** [comment]
Soneone else might need to take this. My python is not a strong point

**Comment by chrismholmes** [comment]
I think @justincely would be interested in getting involved here.

**Comment by joshua-rutherford** [comment]
Let's no over engineer this.  Technically this is only an issue on legacy systems where we don't have a real process manager like systemd.  

Further, I hope we are not using this in container deployments, right.

Lastly, this is an issue against the template, right?

**Comment by justincely** [comment]
PYTHON!!

Yeah, LMK if you need assistance here.  I don't know what this init file is for but i'd be happy to help if need be - may be really quick and easy.

**Comment by chrismholmes** [comment]
This might be off topic but I asked @alecholmez to fully document what he did when he wrapped the python libs last year for @LutherLu1 and @fjt37 when he helped them get their services into the fabric.  It seemed as if the Go SDK was used as a sidecar proxy for python and it is very important for us to understand what he did as a pattern.

**Comment by joshua-rutherford** [comment]
@justincely, have a look at the python file here in respect to Lucas' comments: https://github.com/DecipherNow/gm-fabric-templates/blob/master/default/rpm/init.py

Can you give me an estimate of the time required to update per his comments keeping in mind that this script doesn't have much future given my above comments.
