### ISSUE TITLE
Move Template URI to servgen_settings.toml

### ISSUE THREAD

**Issue by dougfort** [DecipherNow/gm-fabric-go#141]
This will make the fabric command line much cleaner

**Comment by joshua-rutherford** [comment]
I'm okay with allowing the definition of a default there, but this must be overridable via the command line.  In the real world, some people will always generate from a single template, but many will generate from multiple (i.e., for different customers or environments).

**Comment by dougfort** [comment]
We can rig viper to handle that sequence: config-file -> environment variable -> commandline -> default

**Comment by joshua-rutherford** [comment]
That works.
