### ISSUE TITLE
Check 'Minimum Compatible Template Version'

### ISSUE THREAD

**Issue by dougfort** [DecipherNow/gm-fabric-go#142]
See https://github.com/DecipherNow/gm-fabric-templates/issues/20

We have had some errors from users running an older version of the fabric code generator with incompatible templates.

After fetching the templates,  fabric should read ```default/minimimum_fabric_version.txt``` and compare the its version to the minimum version. 

If the fabric version is too old, the program should terminate after displaying a polite message urging the user to upgrade.

**Comment by joshua-rutherford** [comment]
I like this but think it should be part of a larger update to how templates are handled.  I'm going to move this under an epic that talks to updating the templating.

The overlap here is that i think we need to support a new template structure which is effectively:

```
- <root>
  - fabric.toml
  - templates/
    - ...
```
The fabric `.toml` will contain the definitions of a number of things and one could be fabric version.
