### ISSUE TITLE
Suggested improvements

### ISSUE THREAD

**Issue by tilleryd** [DecipherNow/gm-fabric-go#151]
- Include a `.gitignore` file to ignore the vendor dir.  It's likely someone will source control it.  However, this does assume they'll be using Git.
- It would be nice if the docs touched upon the fact that protobuf doesn’t support multipart MIME types.  It's possible to create a work around in `gateway_proxy.go` to execute specific logic based on `multipart` in the `Content-Type` request header but that seems a bit hacky.  It’d be useful to have a well defined escape hatch for situations like this; that is also documented.

**Comment by joshua-rutherford** [comment]
Agreed.  I think we should add the `.gitignore` for `vendor` and `Gopgk.lock`.  See #149 for a rambling discussion and eventual conclusion to why the `Gopkg.lock` is not beneficial.

@tilleryd, I sense some background in a hackathon project I'm missing, but assume @alecholmez has that context.

**Comment by alecholmez** [comment]
We had a `.gitignore` originally, that must've disappeared when we moved the templates. 

I think a document outlining edge cases may be helpful but like I said, I am not 100% protobuf and gRPC don't support multipart/mime. There may be a way we can utilize byte streaming so I wouldn't want to jump to conclusions on that. I would defer to @rfielding for confirmation
