### ISSUE TITLE
Explore Swagger proxy with fabric generator

### ISSUE THREAD

**Issue by dougfort** [DecipherNow/gm-fabric-go#159]
@alecholmez has some existing work on this

**Comment by alecholmez** [comment]
I've only gone as far as to generate a swagger template from a protobuf:

https://github.com/DecipherNow/poa-service/blob/2.0/build.sh#L16

**Comment by dougfort** [comment]
I'm playing with the Swagger Pet Store example. http://petstore.swagger.io/
Using https://github.com/NYTimes/openapi2proto

It doesn't work out of the box; mostly due to deficiencies in the ```fabric``` generator. For example, they use  
```go
(*google_protobuf.Empty, error)
```
which needs this header in the methods:
```go
import google_protobuf "github.com/golang/protobuf/ptypes/empty"
```

I think I can get this working manually in a day or two. By 'manually' I mean 
 * run ```fabric --init swagger_pet_store```
 * run  ```openapi2proto -spec ~/Downloads/swagger.yaml  -options -out swagger_pet_store/protobuf/swagger_pet_store.proto ```
 * run ```fabric --generate swagger_pet_store```

I think this will be worth doing regardless of swagger, just to fix errors in the fabric generator.

Then we can talk about automating it.

There is also the issue of the client, which is more difficult.

**Comment by dougfort** [comment]
Here are the steps to get a running server that (I believe) implements the swagger API through the gateway proxy.

The swagger petshop API is pretty big for a test case. If this is the right direction, I'd like to try to use the swagger tools to create my own API and carry it through to a running server. I think we can use swagger tools to create clients in a variety of languages.

There is also this: https://swagger.io/blog/how-to-perform-a-basic-api-test/

Note that I have to gimmick the output of openapi2proto with ``` sed 's/body: \"body\"/body: "*"/g'``` or protoc won't parse the file. I will investigate that.

1. Run 
```bash
fabric --log-level=debug \
--template=git@github.com:deciphernow/gm-fabric-templates.git//default?ref=29-swagger-petstore-errors \
--init swagger_pet_store
```
2. Download resolved YAML from https://app.swaggerhub.com/apis/dougfort/foot/1.0.0
3. Run
```bash
openapi2proto \
-spec ~/Downloads/swagger.yaml  -options \
| sed 's/body: \"body\"/body: "*"/g' \
> ~/go/src/github.com/dougfort/swagger_pet_store/protobuf/swagger_pet_store.proto
```
4. Run
```bash
fabric --log-level=debug --generate swagger_pet_store
```
5.
```bash
cd swagger_pet_store/
./build_server.sh
```
6. 
```bash
dougfort@pop-os:~/go/src/github.com/dougfort/swagger_pet_store$ $GOPATH/bin/swagger_pet_store --config=settings.toml
2018-02-07T16:35:27-05:00 |INFO| starting service=swagger_pet_store
2018-02-07T16:35:27-05:00 |DEBU| initializing config service=swagger_pet_store
2018-02-07T16:35:27-05:00 |DEBU| not using metrics TLS service=swagger_pet_store
2018-02-07T16:35:27-05:00 |DEBU| not using grpc server TLS service=swagger_pet_store
2018-02-07T16:35:27-05:00 |DEBU| creating listener host= port=10000 service=swagger_pet_store
2018-02-07T16:35:27-05:00 |DEBU| starting metrics server host= port=10001 service=swagger_pet_store
2018-02-07T16:35:27-05:00 |DEBU| starting grpc server service=swagger_pet_store
2018-02-07T16:35:27-05:00 |DEBU| starting gateway proxy service=swagger_pet_store
2018-02-07T16:35:27-05:00 |DEBU| starting gateway proxy server host= port=8080 service=swagger_pet_store
```

**Comment by dougfort** [comment]
I'm experimenting with creating an API from swagger. I'm going to start simple, but I notice all these OAuth templates. Are we interested in any of these?

![screenshot from 2018-02-08 07-16-41](https://user-images.githubusercontent.com/17745/35972723-faef26b2-0ca0-11e8-9646-8401cfd244ba.png)

**Comment by dougfort** [comment]
openapi2proto is worthless. What we really want is https://github.com/googleapis/gnostic

**Comment by joshua-rutherford** [comment]
Bringing the open pull request README.md into her as this is just a discussion issue right now:
# Swagger Proxy

The Gateway Proxy that runs with ta fabric generated server can serve as a proxy for [OpenAPI (Swagger)](https://en.wikipedia.org/wiki/OpenAPI_Specification) APIs.

## SwaggerHub

The best place to start with OpenAPI is [SwaggerHub](https://app.swaggerhub.com).
You can use it to design [your API](https://app.swaggerhub.com/apis/dougfort/Grunt/1.0.0)
It will also generate client code for the proxy.

## openapi2proto

We use the [openapi2proto](https://github.com/NYTimes/openapi2proto) utility to generate
Protocol Buffer Definition files for the fabric genrator.

## Development Process

1. Start your project using the ```fabric``` generator

    ```bash
    fabric --log-level=debug --init sample-project
    ```

1. Use [SwaggerHub](https://app.swaggerhub.com) to design your API.

1. Download YAML (Resolved) from ```SwaggerHub```

1. Use [openapi2proto](https://github.com/NYTimes/openapi2proto) to generate a protocol buffer file for the new project

    ```bash
    openapi2proto -spec ~/Downloads/swagger.yaml -options > sample-project/protobuf/sample-project.proto
    ```

1. Use the ```fabric``` generator to generate method stubs from the protocol buffer definition

    ```bash
    fabric --log-level=debug --generate sample-project
    ```

1. Use an editor to implement some or all of the generated method stubs.

1. Build the fabric service.

    ```bash
    cd sample-project
    ./build-server.sh
    ```

1. Run the server

    ```bash
    $GOPATH/bin/sample-project --config=settings.toml
    ```

1. At this point, you can use a [Swagger tool](https://swagger.io/blog/how-to-perform-a-basic-api-test/) to test the API
1. You can use [Swagger Codegen](https://swagger.io/swagger-codegen/) to generate client API's in a variety of languages. Note that ```SwaggerHub``` will run CodeGen for you: you don't need to install it.
1. The generated client code must be manually added to a client process.

**Comment by joshua-rutherford** [comment]
@dougfort, just getting around to reviewing this and have a few questions.

The idea here was to do this to meet the following use case:

1. Customer provides us their Swagger definition.
1. We generate a proxy that does the following:
    a. Announces the proxied service to ZooKeeper.
    b. Routes all incoming traffic to the appropriate routes on the proxied service.
    c. Collects metrics on the proxied routes.

Reading this, it seem's you have written this such that I can easily do 1, 1.a and 1.c but there is no mention on how to accomplish 1.b.  That is, I'd like this to tie in the client generation for invoking the proxied service.

**Comment by lucasmoten** [comment]
I think 2a and 2c are still in progress due to differences in handling arrays (anonymous ones) with swagger/openapi vs proto and expectations, but beyond that, 2b may need to be some kind of feature flag for whether it should proxy request/response to a target. That's going to be a bit more time consuming to marshal the request from GRPC back into REST or raw HTTP to forward to the backend, and invert on the response

**Comment by alecholmez** [comment]
we've finished work on this
