### ISSUE TITLE
Unable to get info about original peer connecting to Gateway

### ISSUE THREAD

**Issue by lucasmoten** [DecipherNow/gm-fabric-go#166]
Currently, the TLS support for GRPC and Gateway is only supporting encryption through those channels, without conveying any useful information about who is actually making the original connection.

This assumes that connections go as follows
1. From user/service .. as the `peer` to ...
2. Service `gateway` .. as the listening point .. to ..
3. The `grpc` layer, where any info is available in the `context.Context` on the implementation functions, due to gateway_proxy.go leveraging the following
  * setup ... `mux := runtime.NewServeMux(proxymeta.MetaOption(), runtime.WithIncomingHeaderMatcher(rpcutil.MatchHTTPHeaders))`
  * proxymeta.MetaOption() ServeMuxOption appears to add headers of interest defined in https://github.com/DecipherNow/gm-fabric-go/blob/master/metrics/headers/headers_of_interest.go to the map and involves something with routes
  * headers: `runtime.WithIncomingHeaderMatcher(rpcutil.MatchHTTPHeaders)` adds the http headers.

I think this issue can be addressed by analyzing the request and pulling the real peer info

# How I'm trying to get the peer info today from the context
```
func getPeerDN(w context.Context) string {
  p, pok := peer.FromContext(w)
  if pok && p.AuthInfo != nil {
    tlsInfo, ok := p.AuthInfo.(credentials.TLSInfo)
    if ok && tlsInfo.State.HandshakeComplete {
      return tlsutil.GetDistinguishedName(tlsInfo.State.VerifiedChains[0][0])
    }
  }
  return ""
}
```

# Results Using TLS for GRPC + Gateway

settings.toml...
- grpc_use_tls = true
- gateway_use_tls = true
- use_gateway_proxy = true
- server_cert_path/key .. server.cert/key.pem for twl-server-generic2

1. When connecting as tester10,
   - Headers sent from client: none
   - AuthInfo has chain of
     - CN=twl-server-generic2,OU=DAE,OU=DIA,OU=twl-server-generic2,O=U.S. Government,C=US
     - CN=InterCA,OU=chimera,OU=dae,OU=people,O=u.s. government,C=us
   - subject = twl-server-generic2,OU=DAE,OU=DIA,OU=twl-server-generic2,O=U.S. Government,C=US
   - FAIL! Unable to find info that this is from tester10!!!!
   - Operation fails because twl-server-generic2 doesnt have access to tester10 stuff in odrive

2. When connecting as twl-server-generic2
   - Headers sent from client: 
     - user_dn: cn=test tester10,ou=people,ou=dae,ou=chimera,o=u.s. government,c=us
     - external_sys_dn: cn=twl-server-generic2,ou=dae,ou=dia,ou=twl-server-generic2,o=u.s. government,c=us
     - ssl_client_s_dn: cn=twl-server-generic2,ou=dae,ou=dia,ou=twl-server-generic2,o=u.s. government,c=us
   - AuthInfo has chain of
     - CN=twl-server-generic2,OU=DAE,OU=DIA,OU=twl-server-generic2,O=U.S. Government,C=US
     - CN=InterCA,OU=chimera,OU=dae,OU=people,O=u.s. government,C=us
   - In the whitelist, so able to impersonate as user_dn
   - FAIL! .. no validation of the original caller. Effectively same as non TLS (see below)

# Results Using TLS for only GRPC

settings.toml...
- grpc_use_tls = true
- gateway_use_tls = false
- use_gateway_proxy = true
- server_cert_path/key .. server.cert/key.pem for twl-server-generic2

1. When connecting as anonymous and HTTP
   - Headers sent from client: 
     - user_dn: cn=test tester10,ou=people,ou=dae,ou=chimera,o=u.s. government,c=us
     - external_sys_dn: cn=twl-server-generic2,ou=dae,ou=dia,ou=twl-server-generic2,o=u.s. government,c=us
     - ssl_client_s_dn: cn=twl-server-generic2,ou=dae,ou=dia,ou=twl-server-generic2,o=u.s. government,c=us
   - AuthInfo has chain of
     - CN=twl-server-generic2,OU=DAE,OU=DIA,OU=twl-server-generic2,O=U.S. Government,C=US
     - CN=InterCA,OU=chimera,OU=dae,OU=people,O=u.s. government,C=us
   - Able to impersonate as user_dn
   - FAIL! no validation here

# Results Using TLS for only Gateway

settings.toml...
- grpc_use_tls = false
- gateway_use_tls = true
- use_gateway_proxy = true
- server_cert_path/key .. server.cert/key.pem for twl-server-generic2

1. When connecting as tester10,
   - Headers sent from client: none 
   - Routed through as HTTP, and no headers passed
   - FAIL! invalid connection. required headers are missing

2. When connecting as twl-server-generic2
   - Headers sent from client: 
     - user_dn: cn=test tester10,ou=people,ou=dae,ou=chimera,o=u.s. government,c=us
     - external_sys_dn: cn=twl-server-generic2,ou=dae,ou=dia,ou=twl-server-generic2,o=u.s. government,c=us
     - ssl_client_s_dn: cn=twl-server-generic2,ou=dae,ou=dia,ou=twl-server-generic2,o=u.s. government,c=us
   - AuthInfo has nothing!
   - Able to impersonate since its passed in the header..
   - FAIL! there is no peer certificate to verify!

**Comment by lucasmoten** [comment]
Relates to #134

**Comment by lucasmoten** [comment]
Maybe this can be handled with an option like this ?

```
func TLSPeerOption() runtime.ServeMuxOption {
	f := func(ctx oldcontext.Context, req *http.Request) metadata.MD {
		metaMap := make(map[string]string)
		if len(r.TLS.PeerCertificates) {
			metaMap["tls_peer_certificate"] = tlsutil.GetDistinguishedName(r.TLS.PeerCertificates[0])
		}
		return metadata.New(metaMap)
	}
	return runtime.WithMetadata(f)
}
```

**Comment by lucasmoten** [comment]
YES! This will work!!!

**Comment by lucasmoten** [comment]
For cogito-service, I'm throwing this into the main package and added it to customization in gateway_proxy.go.  

```
package main

import (
	"net/http"

	"github.com/deciphernow/gm-fabric-go/tlsutil"
	"github.com/grpc-ecosystem/grpc-gateway/runtime"
	oldcontext "golang.org/x/net/context"
	"google.golang.org/grpc/metadata"
)

// TLSPeerOption sets a metadata value to expose the distinguished name of original connecting peer
func TLSPeerOption() runtime.ServeMuxOption {
	f := func(ctx oldcontext.Context, req *http.Request) metadata.MD {
		metaMap := make(map[string]string)

		if len(req.TLS.PeerCertificates) > 0 {
			metaMap["tls_peer_certificate"] = tlsutil.GetDistinguishedName(req.TLS.PeerCertificates[0])
		}
		return metadata.New(metaMap)
	}
	return runtime.WithMetadata(f)
}
```

We can easily alter the templates to incorporate this in a better location but its unclear to me what would be most suitable given the package naming structure.  Maybe tlsutil

**Comment by dougfort** [comment]
I'd really like a failing test case for this.
