### ISSUE TITLE
Error counting is wrong

### ISSUE THREAD

**Issue by rfielding** [DecipherNow/gm-fabric-go#169]
Http status codes drive state machines on media files that the browser is dealing with.  In general, http codes:
- if less than 300, it's some kind of non-error status.  Example: 206 Partial Content
- if from 400 to 499, it's the caller's fault
- if from 500 or above, it's the web server's fault

This means that generally, a 4xx code is not really a server fault.  It's bad input from the user.  If the codes are done right, then the server won't count these against the server.  But we can track these as user-faults.  These are usually the result of either bad API documentation, misunderstandings, old code vs new API, or malicious attacks.

A 5xx code is a server fault, and should trigger a server code change to fix it; or it may be the fault of a dependency (ie: authentication micro service that we need went down, and it's not the user's fault).

```go
	if c.status != 0 && c.status != http.StatusOK {
		wm.h.metricsChan <- subject.MetricsEvent{
			EventType: "rpc.End",
			RequestID: requestID,
			Timestamp: time.Now(),
			Value:     HTPStatusError{StatusCode: c.status},
			Tags:      wm.h.tags,
		}
	} else {
		wm.h.metricsChan <- subject.MetricsEvent{
			EventType: "rpc.OutPayload",
			RequestID: requestID,
			Timestamp: time.Now(),
			Value:     c.bytesWritten,
			Tags:      wm.h.tags,
		}
		wm.h.metricsChan <- subject.MetricsEvent{
			EventType: "rpc.End",
			RequestID: requestID,
			Timestamp: time.Now(),
			Tags:      wm.h.tags,
		}
	}

**Comment by rfielding** [comment]
In particular: I return a lot of 206 and 304.  These are basic things for range requesting and Etag.  It's an absolute minimum to make large image galleries work efficiently, and for video it's not just more efficient ... the browser will actually break if you don't respect range requests that the browser wants; even if you tell the browser to stop sending them.

**Comment by chrismholmes** [comment]
Are we capturing this information in the Fabric and adding this level of reporting to the overall SDK for metrics?

**Comment by rfielding** [comment]
We should probably at least capture 5xx errors (our fault) vs 4xx errors (caller's fault) difference in our error counting.  For 5xx errors, or certain important URLs, it's probably a good idea to keep detailed counts of exactly which errors.

At Google, they specifically use 5xx error counts to gate the release rate of a product.  4xx error counts are usually good for finding misuses of the API.

**Comment by alecholmez** [comment]
Can we close this?

**Comment by dougfort** [comment]
The related PR has been approved and merge. I'm going to take the liberty of closing this.
