### ISSUE TITLE
Address codeclimate issues to improve score.

### ISSUE THREAD

**Issue by joshua-rutherford** [DecipherNow/gm-fabric-go#175]
This is going to remain a backlog ticket until we get the code climate score up to a respectable level.

**Comment by alecholmez** [comment]
Codeclimate gives me a big headache sometimes. It is EXTREMELY opinionated. For example I got flagged in a project for a function having more than 10 lines *facepalm* which is ridiculous. I ended up just ignoring all the flags and got the score to an A but I feel like that's not a great way to go about this

**Comment by dougfort** [comment]
@alecholmez have you seen this: https://forums.deciphernow.com/t/code-quality-tools/154?

**Comment by alecholmez** [comment]
@dougfort I just saw that. I'll move my feedback there
