### ISSUE TITLE
Serve a JSON list for repeated protobuf elements

### ISSUE THREAD

**Issue by dougfort** [DecipherNow/gm-fabric-go#180]
This is related to #159 and #178 

A problem with the gateway proxy in general (that causes trouble with the swagger client)

If the protocol buffer definition contains repeated items like this:
```proto
message SearchInventoryResponse {
    repeated InventoryItem items = 1;
}
```

the protoc handler for go generates a message like this:
```go
type SearchInventoryResponse struct {
	Items []*InventoryItem `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
}
```

and the gateway proxy marshals it to JSON like this:
```json
{"items":[{"id":"d290f1ee-6c54-4b01-90e6-d701748f0851","name":"Widget Adapter","releaseDate":"1"}]}
```

But what the swagger client (and probably any other HTTP client) wants is just the list:
```go
Items []InventoryItem 
```

which should be represented in JSON like this
```json
[{"id":"d290f1ee-6c54-4b01-90e6-d701748f0851","name":"Widget Adapter","releaseDate":"1"}]
```

So we need to intervene somewhere to strip off the outer 
```json
{"items":}
```

**Comment by lucasmoten** [comment]
It just wants an anonymous array?

**Comment by dougfort** [comment]
Yes. I generated a swagger ```go``` client and then spent most of the day trying to find out why it wouldn't unmarshal the JSON from our gateway proxy.

**Comment by lucasmoten** [comment]
I found this that seems to show the differences for named vs anonymous field for the array.  If I'm reading this correctly, the type (or lack thereof) can influence whether its named or not from a swagger perspective
https://stackoverflow.com/questions/19585581/how-to-describe-a-model-in-swagger-for-an-array-with-simple-objects

On the Proto side to have unnamed, I'm not sure.  This is the closest I found to it, but it seems you may have already tried this?
https://stackoverflow.com/questions/46945555/how-to-model-json-array-as-protobuf-definition

**Comment by dougfort** [comment]
At this stage, I'm trying to compose several sets of generated code with as few changes as possible. The basic workflow is:
 * Edit API description on SwaggerHub
 * Download API Description file
 * Use [openapi2proto]( https://github.com/NYTimes/openapi2proto ) to generate a protocol buffer definition from the API Description
 * Use our fabric generator to generate stub definitions for a server and clients
    * fabric uses protoc to generate grpc and gateway proxy files for go
 * Use SwaggerHub to generate and download a go client API definition
 * Integrate the client API definition  into our generated HTTP client stub

This issue addresses a specific mismatch between the generated client code and the generated server code. The alternatives you have shown are better, but at this stage I'm trying to make the minimum change.

This workflow is what I have stumbled into while investigating OAS (swagger). It may not be what any client wants. But I'm hoping to get a working swagger/fabric hybrid, however crude and then evolve from there.

**Comment by lucasmoten** [comment]
ok. It appears from openapi2proto, that the caveat may be the cause of the "items"
* Endpoints that respond with an array will be wrapped with a message type that has a single field, 'items', that contains the array.

https://github.com/NYTimes/openapi2proto/blob/master/openapi.go#L86

More fun down in https://github.com/NYTimes/openapi2proto/blob/master/openapi.go#L383

**Comment by dougfort** [comment]
Yes, that's it.
