### ISSUE TITLE
zk_connection_string

### ISSUE THREAD

**Issue by rfielding** [DecipherNow/gm-fabric-go#191]
viper.GetStringSlice assumes that strings are whitespace delimited.  We will be passing in ZK_CONNECTION_STRING into docker-compose for launching containers.  The zookeeper url standardized on a comma-delimited list of ip:port pairs.

I modified the auto-generated code expecting space-delimited zookeeper urls to parse by commas:

```
	cancel := gk.Announce(strings.Split(viper.GetString("zk_connection_string"), ","), &gk.Registration{
		Path:   viper.GetString("zk_announce_path") + "/rpc",
		Host:   host,
		Status: gk.Alive,
		Port:   viper.GetInt("grpc_server_port"),
	})
```

So, in this case, we are explicitly parsing it as comma-delimited.  We should do this because there are more clients than this Go code.  Java clients (and zk generally) just expect comma-delimited zk urls  with no whitespace in them.

**Comment by joshua-rutherford** [comment]
This is a template issue as pointed out by @rfielding, closing this in favor of https://github.com/DecipherNow/gm-fabric-templates/issues/35.
