### ISSUE TITLE
Adding Service Methods (Step 3)

### ISSUE THREAD

**Issue by knoebelja** [DecipherNow/gm-fabric-go#192]
Step 3 is as following:

Generate the method stubs for the updated definitions.
fabric --generate "exemplar"

!Needs a note to be done from the "examples" folder

**Comment by joshua-rutherford** [comment]
You should be following the directions here: https://deciphernow.github.io/gm-fabric-documentation/introduction.  This is a valid issue, but we know this is out of date.
