### ISSUE TITLE
Building and Running the Service - Step 3

### ISSUE THREAD

**Issue by knoebelja** [DecipherNow/gm-fabric-go#193]
As a first time user, I wasn't sure what to expect.
I tried accessing the proxy server at localhost:8080 and received a "Not found" message.
This made me unsure of what I was doing, until I just moved onto steps 4 and 5.

**Comment by alecholmez** [comment]
@knoebelja What is the exact url you used to access the server? Did you use the full URL provided in the docs or just go to `localhost:8080`?

**Comment by alecholmez** [comment]
Closing
