### ISSUE TITLE
End step of Enabling TSL, unexpected results

### ISSUE THREAD

**Issue by knoebelja** [DecipherNow/gm-fabric-go#194]
Link does not work after completing all of the steps..!

Received errors:
http: TLS handshake error from [::1]:55210: EOF
http: TLS handshake error from [::1]:55211: tls: client didn't provide a certificate

**Comment by knoebelja** [comment]
I redid the steps and now need a "privateKey" in my keychain.

**Comment by knoebelja** [comment]
I don't know the password.

**Comment by alecholmez** [comment]
The password should be in the chart at the top of the document: `password`

**Comment by joshua-rutherford** [comment]
@knoebelja, please use these instructions: https://deciphernow.github.io/gm-fabric-documentation/introduction

If something is wrong there, we will address it.  This README.md is not updated.

**Comment by knoebelja** [comment]
@joshua-rutherford I'm using those instructions, and posting issues here.
@alecholmez The password "password" does not work.

**Comment by joshua-rutherford** [comment]
Oh, please open issues in https://github.com/DecipherNow/gm-fabric-documentation
