### ISSUE TITLE
container CA trusts

### ISSUE THREAD

**Issue by rfielding** [DecipherNow/gm-fabric-go#199]
When the auto-generated build of an app skeleton happens, it has a Dockerfile that is `FROM ubuntu`.  This may compile and build, but be unable to work with AWS and other services due to certificates not updating.  All containers being built should probably update ca-certificates as the default stance.  So this is now in my Dockerfile:
```
RUN apt-get update
RUN apt-get install -y openssl
RUN apt-get install -y ca-certificates
```

**Comment by alecholmez** [comment]
fixed in gm-fabric-templates https://github.com/DecipherNow/gm-fabric-templates/issues/53
