### ISSUE TITLE
Fix creation/config of TLS Client to work correctly without client cert

### ISSUE THREAD

**Issue by joshua-rutherford** [DecipherNow/gm-fabric-go#2]
https://github.com/DecipherNow/gm-fabric-go/blob/master/tlsutil/tlsclient.go#L50

These functions make blanket assumptions about a client certificate being provided. This should not always be required. There are plenty of use cases where TLS is needed for a trust, but not 2-way SSL.
* NewTLSConfig
* NewTLSClientConfig
* NewTLSClientConn

Recommend refactoring this to model after aspects of Object Drive Server which has been sucessfully doing this from day 1
https://github.com/DecipherNow/object-drive-server/blob/develop/config/AppConfiguration.go#L605

**Comment by alecholmez** [comment]
`tlsutil` supports 1-way ssl
