### ISSUE TITLE
Add a version to metrics JSON output

### ISSUE THREAD

**Issue by dougfort** [DecipherNow/gm-fabric-go#203]
So the Dashboard UI knows what it is getting

**Comment by dougfort** [comment]
I propose too make this version a single int, starting with 1. IMO this is not a case for semantic versioning.

**Comment by alecholmez** [comment]
I think it might be better to do something like:
```json
"version": {
    "major": 1,
    "minor": 0,
    "patch": 5
}
```
just so the dashboard devs have a bit more granular control over the versioning. I feel like having a single int doesn't capture enough version data the dashboard needs

**Comment by dougfort** [comment]
I'm willing to do that, with modifications. The dashboard output is 'flat' Finagle style JSON. So  something like:
```json
dashboard-version: "1.0.0",
```
However, this seems like overkill to me. This is not sophisticated data. I'm interested in what @spmcbride1201 thinks. It's easy to do, either way.

**Comment by alecholmez** [comment]
Ah crap I forgot the dashboard JSON is flat. Let's definitely get Sean's opinion

**Comment by joshua-rutherford** [comment]
I'm not totally with including this in the metrics themselves but I could be argued that it might make sense.  However, it should not be `dashboard-version` if we do include it.  Backend services shouldn't be aware that a dashboard exists at all (unless they exist to power it explicitly).  This would be more appropriately called something like: `fabric-metrics-version`.

**Comment by joshua-rutherford** [comment]
Note that once you do this, this becomes part of you public API and you must semantically version.

**Comment by dougfort** [comment]
This is only going to be visible in the JSON output. That's why I favor a single digit. It's more like:
```
syntax = "proto3";
```
in protobuf.

**Comment by joshua-rutherford** [comment]
The reason you are adding this is because @spmcbride1201 needs to know what metrics are available, therefore it's defining the public API.
