### ISSUE TITLE
go-metrics reporting is unreliable

### ISSUE THREAD

**Issue by dougfort** [DecipherNow/gm-fabric-go#211]
@rfielding  reports that metrics reported like this fail to appear in the JSON metrics output.
```go
 // Count our queue lengths in metrics
    ql := svr.getQueueLengths()
    for k, v := range ql {
        gkey := []string{"gm-data-fabric", "queues", k + "length"}
        gval := float32(v)
        gometrics.SetGauge(gkey, gval)
    }
```
I haven't been able to duplicate this, but my tests use metrics accumulated in grpc methods reached via the gateway proxy. Rob's case involves pure HTTP outside the proxy.

**Comment by rfielding** [comment]
I have an issue in my own repo, and the code that does not show the metrics is actually checked in to current master.

https://github.com/DecipherNow/gm-data-fabric/issues/59

**Comment by rfielding** [comment]
I'm going to call this solved for now.  The global default is a blackhole, and it needs to be overridden from some package (mine!), at which point, normal metrics use works.

The bad counts are a different issue
