### ISSUE TITLE
Content-Length is not necessarily what client read.

### ISSUE THREAD

**Issue by rfielding** [DecipherNow/gm-fabric-go#222]
When doing metrics, I often get extremely overestimated throughput in the graphs.  I am logging the issue here so that it does not get lost.  I see this for both upload and download.  Probable causes:

Upload
=====

In multipart-mime upload, there is no content-length header available.  I usually see upload rates of about 50MB/s, which is believable.  But sometimes when doing uploads in parallel, I can get unbelievable counts in the 1GB/s range.  I don't yet have an opinion on what might cause it yet.

Content-Length use
===============

In file downloads, there is a content-length header, but because of browser behavior the content-length cannot be used as an authoritative count of the number of bytes coming back.  All byte counts in and out must be measured counts.

It is perfectly legal for a server to not read all of an http.Body, or for a client to not read all of an http.Body.  This is actually common in the case of streaming formats like mp4.  If the browser gets a URL and gets a 200 that tells it to expect a 1GB file, it may discover that it's an mp4 file and cut off the connection after only a few hundred kb.  The download rate for that file is not going to be: `contentLength/(stopTime-startTime)`.

I'm not sure what the best way to perform these counts is.  Intercepting r.Body and w.Body with counting readers and writers might be useful for getting counts that ignore headers and encryption overhead.  Intercepting the transport may not interact well with the fact that tcp connections are reused between logical http connections with keep-alive and http/2.

**Comment by dougfort** [comment]
In the prometheus metrics I am intercepting the body in both directions.
