### ISSUE TITLE
Create whitelist middleware

### ISSUE THREAD

**Issue by dougfort** [DecipherNow/gm-fabric-go#225]
Similar to the Oauth middleware, using a whitelist of Distinguished Names

**Comment by dougfort** [comment]
This will be used by  https://github.com/DecipherNow/gm-fabric-proxy to implement https://github.com/DecipherNow/gm-fabric/issues/81

**Comment by dougfort** [comment]
I propose to treat the White/Black lists as lists of (lists of RDNs), with the list of RDNs expressed as a  comma delimited string.

The match algorithm is:
 * an exact (case insensitive) match on every RDN in a row means the DN is governed by the list.
* black list takes precedence over white list 
```json
{
  "userBlacklist": [
    "cn=alec.holmes,dc=deciphernow,dc=com"
  ],
  "userWhitelist": [
    "dc=deciphernow,dc=com"
  ]
}
```
This means that every DN in deciphernow.com is granted access except alec.holmes

**Comment by alecholmez** [comment]
I think this is a valid approach. Do distinguished names need to be case sensitive? I can't see a reason as to why that would matter.

**Comment by dougfort** [comment]
I'm planning to treat them as case INsensitive. CN=ALEC.HOLMES == cn=alec.holmes

**Comment by joshua-rutherford** [comment]
@dougfort and I discussed and the following notes:

1. Case insensitive comparisons.
1. Order independent comparisons between different RDN's, order dependent within RDN's.  Thats, `cn=john.doe,dc=deciphernow,dc=com` == `dc=deciphernow,dc=com,cn=john.doe` but `cn=john.doe,dc=deciphernow,dc=com` != `cn=john.doe,dc=com,dc=deciphernow`.

Also, just to clarify on the implementation.  I assume that the following are equivalent with respect to `cn=john.doe,dc=deciphernow,dc=com`

```
{
  "userBlacklist": [
    "cn=john.doe,dc=deciphernow,dc=com"
  ],
  "userWhitelist": [
    "dc=deciphernow,dc=com"
  ]
}
```
and
```
{
  "userBlacklist": [
    "cn=john.doe"
  ],
  "userWhitelist": [
    "dc=deciphernow,dc=com"
  ]
}
```

**Comment by dougfort** [comment]
Cosed by #229
