### ISSUE TITLE
Global access to main logger

### ISSUE THREAD

**Issue by Minger** [DecipherNow/gm-fabric-go#228]
The logger defined in `cmd/server/main.go` is not available outside `func main()`.  Logger has to be redefined when needed elsewhere. Furthermore, a service level setting like log level has to be re-read in each context.  Fabric users can hack this for ourselves by, for example, setting a package level variable in `config` during `Initialize()` and then `main()`.  However, it would be nice if Fabric provided access to a centrally configured logger out of the box.

https://gobuffalo.io/en/docs/context
```
// actions/context.go
type MyContext struct {
  buffalo.Context
}

func (my MyContext) Error(status int, err error) error {
  my.Logger().Fatal(err)
  return err
}
```

**Comment by dougfort** [comment]
The current templates provide for this

https://github.com/DecipherNow/gm-fabric-templates/blob/master/default/templates/.fabric/templates/new_server.go
