### ISSUE TITLE
Metrics ZK Announcement isn't using comma delimited string

### ISSUE THREAD

**Issue by alecholmez** [DecipherNow/gm-fabric-go#230]
https://github.com/DecipherNow/graph-service/blob/master/graphservice/cmd/server/zk.go#L24

**Comment by dougfort** [comment]
Is that this one? https://github.com/DecipherNow/gm-fabric-templates/pull/36

**Comment by alecholmez** [comment]
Faulty issue. The user edited the generated code and I misinterpreted
