### ISSUE TITLE
List based authorization does not work for impersonation and oauth.

### ISSUE THREAD

**Issue by joshua-rutherford** [DecipherNow/gm-fabric-go#232]
The current implementation of the white and black listing logic only works directly on the client certificate presented to the service.  However, we have many deployments that use impersonation (i.e., the gateway terminates the client's SSL connection and uses it's own certificate for proxied traffic) and OAuth.  In these cases, the presented certificate is only valid for knowing what service is connecting to our service.  We need to know which user the service is impersonating.  The user is indicated in headers in these cases.  See https://github.com/DecipherNow/gm-data-fabric/blob/master/handler/http.go#L287.

**Comment by dougfort** [comment]
This issue applies to gm-fabric-proxy see (#)32
