### ISSUE TITLE
Add a function to the cloudobserver package that checks whether an AWS session's credentials/profile are valid.

### ISSUE THREAD

**Issue by sofiashalotenko** [DecipherNow/gm-fabric-go#270]
One failing on the part of the AWS go sdk (pretty sure it's AWS and not me) is that there is no way to check that your AWS session is valid until you're in the midst of trying to do something. In one-off AWS usage cases (e.g. a single client.ListMetrics command) this is more or less ok (though not ideal in my opinion). When you start dealing with things like our GM services that have ongoing goroutines, it causes the problem that the service (with cloudwatch enabled) runs without any error messages, but the user will be very confused because none of their metrics are coming up on the CloudWatch dashboard. E.g. A user can run the service with aws_access_key = "blahblahblah_obviously_wrong_blahblahblah" and there will be no error message.

I want to add some kind of function that checks the validity of an AWS session and returns an error if the credentials/profile doesn't work. This will be a check beyond what AWS already does which as far as I can tell is just making sure that certain strings aren't empty.

If you're an AWS whiz and know that my impression is wrong, or if there's already a function provided by AWS that can do this, please let me know.

**Comment by alecholmez** [comment]
@sofiashalotenko can this be closed?

**Comment by sofiashalotenko** [comment]
Solution found and currently resides in gm-fabric-go.  Closing.
