### ISSUE TITLE
Impersonation Scenarios

### ISSUE THREAD

**Issue by alecholmez** [DecipherNow/gm-fabric-go#306]
## Scenario 1
`external_sys_dn` will be empty, if that’s the case we go look in `ssl_client_s_dn` for the edge node certificate DN (in this case nginx) and compare that to the whitelist. 
## Scenario 2
compare both `external_sys_dn` and `ssl_client_s_dn` to the whitelist and block the call if neither or only one exist on the ACL filter list. When both `external_sys_dn` and `ssl_client_s_dn` are populated we have to assume both systems are allowed to impersonate the user. 
## Scenario 3
If the proxy were to act as a termination point, the proxy should set `ssl_client_s_dn` header to the proxy's DN.

**Comment by alecholmez** [comment]
Right now the proxy is denying requests if `external_sys_dn` is not populated which is not a valid assumption.

**Comment by chrismholmes** [comment]
How standard is this?  How much of this would not be relevant to any commercial customer?  Is it an option or have we just injected code into a commercial proxy that may not be commercial best practice?

**Comment by joshua-rutherford** [comment]
This is non-standard so the argument could be made to do this elsewhere (i.e., in a client specific library) but the end result will have to be the same: we will have bring that library into the proxy code as a dependency or we cannot support impersonation using this approach in any customer set with that proxy.

Unless we chose to maintain separate binaries for various customers it all has to get compiled into the product at some point.

**Comment by dougfort** [comment]
We could use a plugin. https://golang.org/pkg/plugin/

**Comment by joshua-rutherford** [comment]
Correct me if I'm wrong, but I always heard this was considered undesireable.  Never really got the justification on that but that was my understanding.

**Comment by dougfort** [comment]
Well it seems pretty insecure. I mean someone could hand you any piece of code as your plugin. FWIW we're using a plugin to hook up go code to Envoy.

**Comment by joshua-rutherford** [comment]
It's no more insecure than me running any other code I didn't write.  As always, you must trust the code you execute.
