### ISSUE TITLE
DN whitespaces after commas make them not match with tester certificates 

### ISSUE THREAD

**Issue by hiromis** [DecipherNow/gm-fabric-go#329]
I am having an issue with whitelist.txt in MEME dev. The whitelist.txt contains:
```
CN=twl-server-generic2, OU=DAE, OU=DIA, OU=twl-server-generic2, O=U.S. Government, C=US
C=US, O=U.S. Government, OU=Six 3 Systems, OU=Orion, OU=Servers, CN=dctcdev.pegasus.dodiis.gov
cn=twl-server-generic2,ou=dae,ou=dia,ou=twl-server-generic2,o=u.s. government,c=us
```

The error message says:
```
?[90m2018-08-21T17:46:59Z?[0m |?[31mERRO?[0m| ?[0mServer not on authorized whitelist?[0m ?[36mEXTERNAL_SYS_DN?[0m= ?[36mSSL_CLIENT_S_DN?[0m="CN=twl-server-generic2,OU=DAE,OU=DIA,OU=twl-server-generic2,O=U.S. Government,C=US" ?[36mUSER_DN?[0m="CN=test tester10,OU=People,OU=DAE,OU=chimera,O=U.S. Government,C=US"
```

The difference seems to be whitespaces:
```
CN=twl-server-generic2,OU=DAE,OU=DIA,OU=twl-server-generic2,O=U.S. Government,C=US
CN=twl-server-generic2, OU=DAE, OU=DIA, OU=twl-server-generic2, O=U.S. Government, C=US
```

@fcarbon was also experiencing a similar issue (his was a little more complicated with ordering of repeated OUs) and had a workaround in his project which I could also use if it were available in fabric itself. Could you consider this pull request? 

https://github.com/DecipherNow/gm-fabric-go/pull/328

**Comment by justincely** [comment]
@lucasmoten @joshua-rutherford is whitespace significant in DNs? I presume not, but don't want to assume if that's part of the typical specification.

**Comment by alecholmez** [comment]
DN ordering is important. We shouldn't compare just the values of each field but the whole string. Trimming makes sense but only for the specific ordering we have. What about apache or other DN specs?

**Comment by joshua-rutherford** [comment]
The white space before and after an RDN separator (e.g., `,`) and before and after a name value separator (e.g., `=`) is unimportant and can be trimmed.  

As far as the order of the RDNs, this is the algorithm all the JVM code uses to normalize so might as well match that for the principle of least surprise: https://github.com/DecipherNow/gm-fabric-jvm/blob/master/core/src/main/scala/com/deciphernow/server/security/DNHelper.scala#L28
