### ISSUE TITLE
Cloudwatch metrics integration is limited to only a handful of the metrics

### ISSUE THREAD

**Issue by justincely** [DecipherNow/gm-fabric-go#362]
Specifically: those outlined in this function: https://github.com/DecipherNow/gm-fabric-go/blob/master/metrics/cloudobserver/cloudobserver.go#L386

If possible; we need to allow any GreyMatter metric to be reported.

**Comment by dougfort** [comment]
https://docs.aws.amazon.com/sdk-for-go/api/service/cloudwatch/cloudwatchiface/

**Comment by dougfort** [comment]
This is the some of what we get from 
```golang
	output, err := co.cwClient.ListMetrics(
		&cloudwatch.ListMetricsInput{
			// Dimensions: co.dimensions,
			// MetricName: aws.String(fmt.Sprintf("%s/%s", testKey, "latency_ms.avg")),
			Namespace: aws.String(co.namespace),
		},
	)
```
```
    {
      Dimensions: [{
          Name: "ServiceName",
          Value: "gm-proxy"
        },{
          Name: "AutoScalingGroupName",
          Value: "test-proxy-asg"
        }],
      MetricName: "route/acme/services/catalog/GET/latency_ms.count",
      Namespace: "GM/EC2"
    },
    {
      Dimensions: [{
          Name: "ServiceName",
          Value: "gm-proxy"
        },{
          Name: "AutoScalingGroupName",
          Value: "test-proxy-asg"
        }],
      MetricName: "route/acme/services/catalog/GET/latency_ms.min",
      Namespace: "GM/EC2"
    }
```

**Comment by dougfort** [comment]
Restrictions on CloudWatch metrics:

* ```cw_metrics_routes```: a regular expression identifying routes to select. Defaults to ```^all$```
* ```cw_metrics_values```: comma separated list of the following:
	* latency_ms.avg
	* latency_ms.count
	* latency_ms.max
	* latency_ms.min
	* latency_ms.sum
	* 
	* latency_ms.p90
	* latency_ms.p95
	* latency_ms.p99
	* latency_ms.p999
	* latency_ms.p9999
	* errors.count
	* in_throughput
	* out_throughput
    Defaults to "latency_ms.count, latency_ms.p50, latency_ms.p9999, in_throughput, out_throughput"

**Comment by justincely** [comment]
@dougfort love it.  What about specifying the system metrics: cpu and mem?

**Comment by dougfort** [comment]
We can do that if we must, but IMO these figures are pointless. I think we're perpetuating them because they are in the JVM dashboard. If you want them it's not hard to add them.

https://www.psychologytoday.com/us/blog/thinking-makes-it-so/201402/the-pot-roast-principle

**Comment by justincely** [comment]
perfect, thanks @dougfort
