### ISSUE TITLE
Modify metrics APIStats to handle long running transactions

### ISSUE THREAD

**Issue by dougfort** [DecipherNow/gm-fabric-go#373]
See https://github.com/DecipherNow/gm-proxy/issues/192

We need to metrics acquisition to handle long running transactions from gm-data.  Note that @alecholmez brought up the same problems with the Envoy backplane.  https://github.com/DecipherNow/gm-fabric-go/issues/249

This is the current metrics stats record, stored in a circular buffer for metrics reporting.
See https://github.com/DecipherNow/gm-fabric-go/blob/master/metrics/grpcobserver/observer.go#L72
```golang
// APIStats reports stats on an individual API call
type APIStats struct {
	RequestID     string
	Key           string
	Transport     subject.EventTransport
	HTTPStatus    int
	PrevRoute     string
	Err           error
	BeginTime     time.Time
	EndTime       time.Time
	InWireLength  int64
	OutWireLength int64
}
```
Here is a proposed replacement for the ```APIStats``` record. The key difference is that we assume that the request body can be read and the response body can be written long after the response headers are sent.

```golang
// APIStats reports stats on an individual API call
type APIStats struct {
	RequestID  string
	Key        string
	Transport  subject.EventTransport
	HTTPStatus int
	PrevRoute  string
	Err        error

	// BeginTime is the earliest point that we can store a timestamp
	BeginTime time.Time

	// RequestTime is the time when an HTTP request is available, with all headers
	// received
	// Latency = RequestTime - BeginTime
	RequestTime time.Time

	// ResponseTime is the time when an HTTP response is sent
	ResponseTime time.Time

	// CaptureTime is the time when metrics are captured
	// This may be the same as EndTime for short transactions
	// but may be earlier for long running transactions.
	CaptureTime time.Time

	// EndTime is the time when the transaction is completely ended
	// We may not capture this time for long running transactions
	EndTime time.Time

	// InWireLength is the amount of data received from the request body
	// at CaptureTime
	// InThroughput = InWireLength / (CaptureTime - RequestTime)
	InWireLength int64

	// OutWireLength is the amount of data sent from the response body
	// at CaptureTime
	// OutThroughput = OutWireLength / (CaptureTime - RequestTime)
	OutWireLength int64
}
```

**Comment by dougfort** [comment]
Oh, I just realized that we need separate ```InputCaptureTime``` and ```OutputCaptureTime``` to compute throughput. One stream could  finish long before the other.

**Comment by dougfort** [comment]
We also need to change the prometheus code:

```golang

**Comment by justincely** [comment]
@rfielding do you see anything missing here?

**Comment by rfielding** [comment]
it definitely looks right for the case of GET where we want to ignore the response body that happens after we get an http response code.

i presume that the list of timestamps is sorted in increasing order in the struct.  I'm still not sure about for requests though.

```go
	BeginTime time.Time
	RequestTime time.Time
	ResponseTime time.Time
	CaptureTime time.Time
	EndTime time.Time
```

If `RequestTime - RequestTime` is the time between when receiving request headers to getting a response code, it covers both the time sending the request body, and the delay until a response code comes back.   If that delta is subtracted out, then, `RequestTime - BeginTime` is just the time to send the request headers.  If there were a large delay from RequestTime to ResponseTime (ie: a POST /write that upoloads a 1GB file), we don't have a timestamp for sending the last byte of the request body.

**Comment by dougfort** [comment]
Could not the request body go on for hours?

**Comment by dougfort** [comment]
My plan is to set a timer for a fairly short interval after receiving the response headers. When the timer expires, we stop tracking this transaction and compute throughput from the number of bytes so far divided by the timer interval.

**Comment by alecholmez** [comment]
@rfielding ^

**Comment by justincely** [comment]
@Hoggles is looking into this in #375

**Comment by dougfort** [comment]
I think this is done
