### ISSUE TITLE
Metrics API needed

### ISSUE THREAD

**Issue by jack-bischoff** [DecipherNow/gm-fabric-go#393]
The metric server crashes with field not found in a service I'm currently working. The fabric api has changed, but the breaking changes have not been reflected in the documentation so I do not know if the field has been replaced or deprecated entirely.

**Comment by jack-bischoff** [comment]
The problem, in particular, is with the grpcObserver.Report field.

**Comment by alecholmez** [comment]
The service in mind as the following metrics server construction:
```go
// Create the metrics observer

	// Create Observers
	grpcObserver := grpcobserver.New(srvcConf.MetricsCacheSize)
	goMetObserver := gometricsobserver.New()

	// Create Subject from Observer(s) (This creates the metrics event channel)
	metricsChan := subject.New(context.Background(), grpcObserver, goMetObserver)

	// Start Metrics Server
	err = ms.Start(
		fmt.Sprintf(":%d", srvcConf.MetricsPort),
		cfg, //  *tls.Config
		grpcObserver.Report,
		goMetObserver.Report,
	)
	// handle error ...
	if err != nil {
		panic(err)
	}

	// Create Source(s) tied to the metrics event channel
	goMetricsSource := gmfabricsink.New(metricsChan)
	gometrics.NewGlobal(gometrics.DefaultConfig("poa"), goMetricsSource)

	httpm := httpmetrics.New(metricsChan)
```
The previous creates the following error:
```
main.go:145:15: grpcObserver.Report undefined (type *grpcobserver.GRPCObserver has no field or method Report)
```
I believe the gm-fabric-go metrics external API has changed and this code is no longer correct in the service. @dougfort can you validate this and provide some new documentation in the metrics package? This service is using the http metrics wrapper if that helps.

**Comment by dougfort** [comment]
Do we support the metrics server in gm-fabric-go? I thought everything goes through gm-proxy now.

**Comment by chrismholmes** [comment]
Everything should be through the proxy, including these Go services.

**Comment by jack-bischoff** [comment]
So, what is the recourse here? Simply cull all code regarding the metrics functionality?

**Comment by alecholmez** [comment]
Yes I think you need to remove all metrics code from your service. I'm closing this and we can work that out offline
