### ISSUE TITLE
Fetcher only works for personal account?

### ISSUE THREAD

**Issue by alecholmez** [DecipherNow/gm-fabric-go#76]
`go-getter` seems to only fetch files successfully from my person git. For example:
```
github.com/alecholmez/Messenger/main.go
```
will resolve no problem on my local machine but something from open source like:
```
github.com/uikit/uikit/package.json
```
or
```
github.com/deciphernow/gm-fabric-go/cmd/templates/server.go
```
do not resolve successfully. Git throws an error saying they do not exist.

**Comment by dougfort** [comment]
How about github.com/deciphernow/gm-fabric-go?

**Comment by alecholmez** [comment]
Apparently the docs just aren't clear. You are right.

I tried `github.com/deciphernow/gm-fabric-go/README.md` because the README is at root and that worked just fine.

**Comment by alecholmez** [comment]
Moving away from go-getter. Deprecating
