### ISSUE TITLE
A newly built service using the instructions fail.

### ISSUE THREAD

**Issue by joshua-rutherford** [DecipherNow/gm-fabric-go#79]
I'm not sure why this is but, I built a service using the instructions on the readme and when I hit the service via the gateway I get the following:

```
{
"error": "all SubConns are in TransientFailure",
"code": 14
}
```

**Comment by joshua-rutherford** [comment]
@dougfort and @alecholmez, this is a priority as it's blocking efforts elsewhere.

**Comment by alecholmez** [comment]
Investigating...

**Comment by dougfort** [comment]
I think this was caused by running an old version of ```fabric```.

**Comment by alecholmez** [comment]
Solved with upgrading
