### ISSUE TITLE
The README.md no longer works with the current templates.

### ISSUE THREAD

**Issue by joshua-rutherford** [DecipherNow/gm-fabric-go#80]
Specifically, this commit broke the build script: https://github.com/DecipherNow/gm-fabric-go/commit/f829ee9a33f5eb57d895b1709bd4e3069432b28e#diff-b1ff52b8263d85a769add4a0c384ebe4.

It now requires that I run the script from within a specific directory.

**Comment by dougfort** [comment]
https://github.com/DecipherNow/gm-fabric-go/issues/49
